In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Demo.xlsx")

In [3]:
df.head()

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,1,RAVAL MEET MAHESH,1131,NaN,29.0,96.666667,44.0,41,85.0,M
1,2,HUMBE BHAKTI RAJENDRA,1107,79.071429,29.0,96.666667,42.0,41,83.0,F
2,3,MARATHE SANSKRUTI JAGDISH,995,71.071429,27.0,90.000000,41.0,41,82.0,F
3,4,THAKARE MRUNALI VINOD,1077,76.928571,28.0,93.333333,43.0,39,82.0,F
4,5,BHONGALE OMKAR MADHUKAR,1064,76.000000,28.0,93.333333,42.0,38,80.0,M

In [4]:
df.shape

(74, 10)

In [5]:
df.columns

Index(['Roll no', 'Name of Student',
       'Previous Year SPPU Total Marks out of  1400', '%', 'UT 1 Marks', '%.1',
       '50% maks of Previous Year SPPU Result', '50% Marks of Unit Test 1',
       'Total 100%', 'Gender '],
      dtype='object')

In [6]:
df.dtypes

Roll no                                          int64
Name of Student                                 object
Previous Year SPPU Total Marks out of  1400      int64
%                                              float64
UT 1 Marks                                     float64
%.1                                            float64
50% maks of Previous Year SPPU Result          float64
50% Marks of Unit Test 1                         int64
Total 100%                                     float64
Gender                                          object
dtype: object

In [7]:
df.isnull().sum()

Roll no                                        0
Name of Student                                0
Previous Year SPPU Total Marks out of  1400    0
%                                              2
UT 1 Marks                                     2
%.1                                            3
50% maks of Previous Year SPPU Result          1
50% Marks of Unit Test 1                       0
Total 100%                                     0
Gender                                         0
dtype: int64

In [12]:
avg=df['%'].mean()

In [13]:
df['%'].fillna(avg,inplace=True)

/var/folders/q5/sxf7pxfx325bnp0p8jl4nyt80000gn/T/ipykernel_1847/4150232176.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['%'].fillna(avg,inplace=True)

In [16]:
df

,Roll no,Name of Student,Previous Year SPPU Total Marks out of 1400,%,UT 1 Marks,%.1,50% maks of Previous Year SPPU Result,50% Marks of Unit Test 1,Total 100%,Gender
0,1,RAVAL MEET MAHESH,1131,68.197421,29.0,96.666667,44.000000,41,85.000000,M
1,2,HUMBE BHAKTI RAJENDRA,1107,79.071429,29.0,96.666667,42.000000,41,83.000000,F
2,3,MARATHE SANSKRUTI JAGDISH,995,71.071429,27.0,90.000000,41.000000,41,82.000000,F
3,4,THAKARE MRUNALI VINOD,1077,76.928571,28.0,93.333333,43.000000,39,82.000000,F
4,5,BHONGALE OMKAR MADHUKAR,1064,76.000000,28.0,93.333333,42.000000,38,80.000000,M
...,...,...,...,...,...,...,...,...,...,...
69,70,KUNWAR ABHIJEET SINGH,725,51.785714,13.0,43.333333,25.892857,29,54.892857,F
70,71,TUPE OM KISHOR,756,54.000000,4.0,13.333333,27.000000,25,52.000000,F
71,72,DARWEY RUDRA GUNWANT,608,43.428571,26.0,86.666667,21.714286,29,50.714286,F
72,73,JAGTAP HARISH YUVRAJ,542,68.197421,18.0,60.000000,0.000000,31,31.000000,F
73,74,ASHUTOSH RAJ,646,46.142857,14.0,46.666667,23.071429,22,45.071429,F

In [15]:
df.isnull().sum()

Roll no                                        0
Name of Student                                0
Previous Year SPPU Total Marks out of  1400    0
%                                              0
UT 1 Marks                                     2
%.1                                            3
50% maks of Previous Year SPPU Result          1
50% Marks of Unit Test 1                       0
Total 100%                                     0
Gender                                         0
dtype: int64